/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 donut.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/donut.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Donut004.geometry} material={materials['Material.007']} position={[-0.244, 0.12, 0.051]} rotation={[3.092, -1.038, 3.041]}>
        <mesh geometry={nodes.Icing004.geometry} material={materials['PINK ICING']} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/donut.gltf')
