/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 icecream.gltf --transform 
Files: icecream.gltf [278.66KB] > C:\Users\Admin\Desktop\model\tako_ice_cream\icecream-transformed.glb [170.98KB] (39%)
Author: BunnyGame (https://sketchfab.com/bunnyGame)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/tako-ice-cream-a62f6338aeeb418091d9d3f379508fb3
Title: Tako Ice Cream
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/icecream-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} position={[-0.009, -1.671, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} position={[0.017, 1.142, -0.611]} rotation={[-0.547, 0, 0]} scale={0.526} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Material} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/icecream-transformed.glb')
