/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/for export.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.body.geometry}
        material={materials['body skin']}
        position={[0, 4.081, -0.213]}
      />
      <group position={[-0.034, 4.193, -0.182]} scale={1.421}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath001.geometry}
          material={materials['front with gradient - pog SHADOW']}
          position={[0.025, 0.615, 0.046]}
          rotation={[0.002, -0.435, -0.349]}
          scale={0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath002.geometry}
          material={materials['front with gradient - pos SHADOW']}
          position={[0.07, 0.615, 0.596]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath003.geometry}
          material={materials['front with gradient - pos SHADOW']}
          position={[0.07, 0.615, 0.596]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath004.geometry}
          material={materials['front with gradient - neg']}
          position={[0.025, 0.615, 0.046]}
          rotation={[0.002, -0.657, 2.793]}
          scale={-0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath005.geometry}
          material={materials['front with gradient - pog SHADOW']}
          position={[0.025, 0.615, 0.046]}
          rotation={[-3.14, -0.435, -0.349]}
          scale={-0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath006.geometry}
          material={materials['front with gradient - neg']}
          position={[0.025, 0.615, 0.046]}
          rotation={[-3.139, -0.657, 2.793]}
          scale={0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath007.geometry}
          material={materials['front with gradient - pos']}
          position={[-0.713, -0.206, 0.14]}
          rotation={[0, 0, 1.796]}
          scale={0.309}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath008.geometry}
          material={materials['front with gradient - pos']}
          position={[-0.568, -0.424, 0.493]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath009.geometry}
          material={materials['front with gradient - pos']}
          position={[0.598, -0.424, 0.493]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={-0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath010.geometry}
          material={materials['front with gradient - pos']}
          position={[0.756, -0.206, 0.14]}
          rotation={[-Math.PI, 0, 1.796]}
          scale={-0.309}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath011.geometry}
          material={materials['front with gradient - BACK']}
          position={[-0.564, 0.453, -0.34]}
          rotation={[0, -0.487, Math.PI / 2]}
          scale={0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath012.geometry}
          material={materials['front with gradient - BACK']}
          position={[0.613, 0.453, -0.34]}
          rotation={[-Math.PI, -0.487, Math.PI / 2]}
          scale={-0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath013.geometry}
          material={materials['front with gradient - BACK']}
          position={[0.03, 0.053, -0.6]}
          rotation={[-1.207, 0, 0]}
          scale={[0.704, 0.356, 0.653]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath014.geometry}
          material={materials['front with gradient - BACK']}
          position={[-0.902, -0.099, 0.005]}
          rotation={[0, 0, 1.544]}
          scale={0.704}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NurbsPath015.geometry}
          material={materials['front with gradient - BACK']}
          position={[0.957, -0.099, 0.005]}
          rotation={[Math.PI, 0, 1.544]}
          scale={-0.704}
        />
      </group>
      <group position={[-0.798, 3.72, -0.186]} scale={[0.161, 0.161, 0.089]}>
        <mesh
          name="Cube006"
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials.ear}
          morphTargetDictionary={nodes.Cube006.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube006.morphTargetInfluences}
        />
        <mesh
          name="Cube006_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials['Material.006']}
          morphTargetDictionary={nodes.Cube006_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube006_1.morphTargetInfluences}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.HAIR.geometry}
        material={materials['front with gradient - pog']}
        position={[0.065, 5.067, -0.108]}
        rotation={[-0.06, -Math.PI / 2, 0]}
        scale={0.765}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.head.geometry}
        material={materials['face base']}
        position={[0, 5.263, 1.265]}
        scale={[-0.23, -1.326, -0.23]}
      />
      <mesh
        name="iris001"
        castShadow
        receiveShadow
        geometry={nodes.iris001.geometry}
        material={materials.iris}
        morphTargetDictionary={nodes.iris001.morphTargetDictionary}
        morphTargetInfluences={nodes.iris001.morphTargetInfluences}
        position={[-0.404, 3.668, 0.174]}
        rotation={[1.64, 0.172, -0.085]}
        scale={0.284}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PONY_L.geometry}
        material={materials['front with gradient - neg']}
        position={[-1.167, 3.139, -0.592]}
        rotation={[-2.787, -0.179, -1.556]}
        scale={[-1.031, -1.394, -1.274]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PONY_R.geometry}
        material={materials['front with gradient - neg']}
        position={[1.105, 3.139, -0.592]}
        rotation={[0.355, -0.179, -1.556]}
        scale={[1.031, 1.394, 1.274]}
      />
    </group>
  )
}

useGLTF.preload('/for export.glb')