/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 comp.gltf 
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/comp.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.95, 3.571, 0.343]} rotation={[0.126, 0.42, 0.124]} scale={[0.161, 0.161, 0.089]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.ear} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['neck ring']} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials['neon - BLUE']} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['body skin']} />
        <mesh geometry={nodes.Cube006_4.geometry} material={materials.strap} />
        <mesh geometry={nodes.Cube006_5.geometry} material={materials.neon} />
        <mesh geometry={nodes.Cube006_6.geometry} material={materials['3-镭射-渐变镭射条']} />
        <mesh geometry={nodes.Cube006_7.geometry} material={materials['laser- advanced']} />
        <mesh geometry={nodes.Cube006_8.geometry} material={materials.belt} />
        <mesh geometry={nodes.Cube006_9.geometry} material={materials.suit} />
        <mesh geometry={nodes.Cube006_10.geometry} material={materials['laser- advanced.001']} />
        <mesh geometry={nodes.Cube006_11.geometry} material={materials['shoe body']} />
        <mesh geometry={nodes.Cube006_12.geometry} material={materials['shoe face']} />
        <mesh geometry={nodes.Cube006_13.geometry} material={materials['laser- advanced GREEN']} />
        <mesh geometry={nodes.Cube006_14.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube006_15.geometry} material={materials['face base']} />
        <mesh geometry={nodes.Cube006_16.geometry} material={materials['front with gradient - pog']} />
        <mesh geometry={nodes.Cube006_17.geometry} material={materials['front with gradient - pog SHADOW']} />
        <mesh geometry={nodes.Cube006_18.geometry} material={materials['front with gradient - pos SHADOW']} />
        <mesh geometry={nodes.Cube006_19.geometry} material={materials['front with gradient - neg']} />
        <mesh geometry={nodes.Cube006_20.geometry} material={materials['front with gradient - pos']} />
        <mesh geometry={nodes.Cube006_21.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Cube006_22.geometry} material={materials['front with gradient - BACK']} />
        <mesh geometry={nodes.Cube006_23.geometry} material={materials['strap inverse']} />
        <mesh geometry={nodes.Cube006_24.geometry} material={materials['neon - GREEN']} />
        <mesh geometry={nodes.Cube006_25.geometry} material={materials['3-镭射-渐变镭射条 inverse']} />
        <mesh geometry={nodes.Cube006_26.geometry} material={materials['laser- advanced inverse']} />
        <mesh geometry={nodes.Cube006_27.geometry} material={materials['shoe body inverse']} />
        <mesh geometry={nodes.Cube006_28.geometry} material={materials['shoe face inverse']} />
        <mesh geometry={nodes.Cube006_29.geometry} material={materials['laser- advanced inverse.001']} />
        <mesh geometry={nodes.Cube006_30.geometry} material={materials['belt inverse']} />
        <mesh geometry={nodes.Cube006_31.geometry} material={materials['laser- advanced inverse.002']} />
        <mesh geometry={nodes.Cube006_32.geometry} material={materials['ear - inverse']} />
        <mesh geometry={nodes.Cube006_33.geometry} material={materials['neon purple']} />
        <mesh geometry={nodes.Cube006_34.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cube006_35.geometry} material={materials['face base - Inverse']} />
        <mesh geometry={nodes.Cube006_36.geometry} material={materials['front with gradient - pog inverse']} />
        <mesh geometry={nodes.Cube006_37.geometry} material={materials['front with gradient - pos SHADOW inverse']} />
        <mesh geometry={nodes.Cube006_38.geometry} material={materials['front with gradient - pog SHADOW inverse']} />
        <mesh geometry={nodes.Cube006_39.geometry} material={materials['front with gradient - neg - inverse']} />
        <mesh geometry={nodes.Cube006_40.geometry} material={materials['front with gradient - pos inverse']} />
        <mesh geometry={nodes.Cube006_41.geometry} material={materials['front with gradient - BACK inverse']} />
        <mesh geometry={nodes.Cube006_42.geometry} material={materials['pony with gradient inverse']} />
        <mesh geometry={nodes.Cube006_43.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube006_44.geometry} material={materials['suit inverse']} />
      </group>
    </group>
  )
}

useGLTF.preload('/comp.gltf')
