/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 Compressed-emb.gltf 
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Compressed-emb.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.81, 5.007, -0.839]} rotation={[1.648, 0.005, -0.313]} scale={0.432}>
        <mesh geometry={nodes.Torus006.geometry} material={materials['3-镭射-渐变镭射条 inverse']} />
        <mesh geometry={nodes.Torus006_1.geometry} material={materials['laser- advanced inverse']} />
        <mesh geometry={nodes.Torus006_2.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Torus006_3.geometry} material={materials['face base - Inverse']} />
        <mesh geometry={nodes.Torus006_4.geometry} material={materials.strap} />
        <mesh geometry={nodes.Torus006_5.geometry} material={materials['neon - BLUE']} />
        <mesh geometry={nodes.Torus006_6.geometry} material={materials['neck ring']} />
        <mesh geometry={nodes.Torus006_7.geometry} material={materials['strap inverse']} />
        <mesh geometry={nodes.Torus006_8.geometry} material={materials['neon - GREEN']} />
        <mesh geometry={nodes.Torus006_9.geometry} material={materials.Material} />
        <mesh geometry={nodes.Torus006_10.geometry} material={materials['suit inverse']} />
        <mesh geometry={nodes.Torus006_11.geometry} material={materials['belt inverse']} />
        <mesh geometry={nodes.Torus006_12.geometry} material={materials['laser- advanced inverse.002']} />
        <mesh geometry={nodes.Torus006_13.geometry} material={materials['shoe body inverse']} />
        <mesh geometry={nodes.Torus006_14.geometry} material={materials['shoe face inverse']} />
        <mesh geometry={nodes.Torus006_15.geometry} material={materials['laser- advanced inverse.001']} />
        <mesh geometry={nodes.Torus006_16.geometry} material={materials['pony with gradient inverse']} />
        <mesh geometry={nodes.Torus006_17.geometry} material={materials['front with gradient - pog inverse']} />
        <mesh geometry={nodes.Torus006_18.geometry} material={materials['front with gradient - pos SHADOW inverse']} />
        <mesh geometry={nodes.Torus006_19.geometry} material={materials['front with gradient - pog SHADOW inverse']} />
        <mesh geometry={nodes.Torus006_20.geometry} material={materials['front with gradient - neg - inverse']} />
        <mesh geometry={nodes.Torus006_21.geometry} material={materials['front with gradient - pos inverse']} />
        <mesh geometry={nodes.Torus006_22.geometry} material={materials['front with gradient - BACK inverse']} />
        <mesh geometry={nodes.Torus006_23.geometry} material={materials['ear - inverse']} />
        <mesh geometry={nodes.Torus006_24.geometry} material={materials['neon purple']} />
        <mesh geometry={nodes.Torus006_25.geometry} material={materials.ear} />
        <mesh geometry={nodes.Torus006_26.geometry} material={materials['front with gradient - pos']} />
        <mesh geometry={nodes.Torus006_27.geometry} material={materials['3-镭射-渐变镭射条']} />
        <mesh geometry={nodes.Torus006_28.geometry} material={materials['laser- advanced']} />
        <mesh geometry={nodes.Torus006_29.geometry} material={materials['front with gradient - pog']} />
        <mesh geometry={nodes.Torus006_30.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Torus006_31.geometry} material={materials['front with gradient - pog SHADOW']} />
        <mesh geometry={nodes.Torus006_32.geometry} material={materials['front with gradient - pos SHADOW']} />
        <mesh geometry={nodes.Torus006_33.geometry} material={materials['front with gradient - neg']} />
        <mesh geometry={nodes.Torus006_34.geometry} material={materials['front with gradient - BACK']} />
        <mesh geometry={nodes.Torus006_35.geometry} material={materials['face base']} />
        <mesh geometry={nodes.Torus006_36.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Torus006_37.geometry} material={materials['body skin']} />
        <mesh geometry={nodes.Torus006_38.geometry} material={materials.neon} />
        <mesh geometry={nodes.Torus006_39.geometry} material={materials.belt} />
        <mesh geometry={nodes.Torus006_40.geometry} material={materials.suit} />
        <mesh geometry={nodes.Torus006_41.geometry} material={materials['laser- advanced.001']} />
        <mesh geometry={nodes.Torus006_42.geometry} material={materials['shoe body']} />
        <mesh geometry={nodes.Torus006_43.geometry} material={materials['shoe face']} />
        <mesh geometry={nodes.Torus006_44.geometry} material={materials['laser- advanced GREEN']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Compressed-emb.gltf')
