/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 starsemb.gltf 
*/

import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/starsemb.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dobj.geometry} material={materials['3-镭射-渐变镭射条.dia']} position={[-0.967, 2.877, 0]} rotation={[0.667, -0.528, 0.507]} scale={0.259} />
      <group position={[0.017, 2.433, 0]} rotation={[-2.07, 0.185, 0.411]} scale={0.884}>
        <mesh geometry={nodes.Star_1.geometry} material={materials['3-镭射-渐变镭射条']} />
        <mesh geometry={nodes.Star_2.geometry} material={materials.neon} />
      </group>
      <group position={[-0.873, 1.705, 0]} rotation={[-1.504, 0.504, -0.688]} scale={0.293}>
        <mesh geometry={nodes.Star001_1.geometry} material={materials['3-镭射-渐变镭射条 inverse']} />
        <mesh geometry={nodes.Star001_2.geometry} material={materials['neon - BLUE']} />
      </group>
      <group position={[1.07, 2.876, 0]} rotation={[0.207, -1.099, 1.694]} scale={0.361}>
        <mesh geometry={nodes.Star002_1.geometry} material={materials['3-镭射-渐变镭射条 inverse']} />
        <mesh geometry={nodes.Star002_2.geometry} material={materials['neon purple']} />
      </group>
      <mesh geometry={nodes.dobj001.geometry} material={materials['3-镭射-渐变镭射条 inverse dia']} position={[0.916, 2.039, 0]} rotation={[1.418, 0.934, -1.219]} scale={0.176} />
    </group>
  )
}

useGLTF.preload('/starsemb.gltf')
